const allCountries = [
  { code: "PK", name: "Pakistan", callingCode: "92", flag: "🇵🇰" },
  { code: "US", name: "United States", callingCode: "1", flag: "🇺🇸" },
  { code: "IN", name: "India", callingCode: "91", flag: "🇮🇳" },
  { code: "GB", name: "United Kingdom", callingCode: "44", flag: "🇬🇧" },
  {
    code: "AE",
    name: "United Arab Emirates",
    callingCode: "971",
    flag: "🇦🇪",
  },
  { code: "SA", name: "Saudi Arabia", callingCode: "966", flag: "🇸🇦" },
  { code: "CA", name: "Canada", callingCode: "1", flag: "🇨🇦" },
  { code: "AU", name: "Australia", callingCode: "61", flag: "🇦🇺" },
  { code: "DE", name: "Germany", callingCode: "49", flag: "🇩🇪" },
  { code: "FR", name: "France", callingCode: "33", flag: "🇫🇷" },
  { code: "IT", name: "Italy", callingCode: "39", flag: "🇮🇹" },
  { code: "ES", name: "Spain", callingCode: "34", flag: "🇪🇸" },
  { code: "BR", name: "Brazil", callingCode: "55", flag: "🇧🇷" },
  { code: "CN", name: "China", callingCode: "86", flag: "🇨🇳" },
  { code: "JP", name: "Japan", callingCode: "81", flag: "🇯🇵" },
  { code: "KR", name: "South Korea", callingCode: "82", flag: "🇰🇷" },
  { code: "RU", name: "Russia", callingCode: "7", flag: "🇷🇺" },
  { code: "TR", name: "Turkey", callingCode: "90", flag: "🇹🇷" },
  { code: "EG", name: "Egypt", callingCode: "20", flag: "🇪🇬" },
  { code: "ZA", name: "South Africa", callingCode: "27", flag: "🇿🇦" },
  { code: "NG", name: "Nigeria", callingCode: "234", flag: "🇳🇬" },
  { code: "KE", name: "Kenya", callingCode: "254", flag: "🇰🇪" },
  { code: "BD", name: "Bangladesh", callingCode: "880", flag: "🇧🇩" },
  { code: "ID", name: "Indonesia", callingCode: "62", flag: "🇮🇩" },
  { code: "MY", name: "Malaysia", callingCode: "60", flag: "🇲🇾" },
  { code: "TH", name: "Thailand", callingCode: "66", flag: "🇹🇭" },
  { code: "VN", name: "Vietnam", callingCode: "84", flag: "🇻🇳" },
  { code: "PH", name: "Philippines", callingCode: "63", flag: "🇵🇭" },
  { code: "SG", name: "Singapore", callingCode: "65", flag: "🇸🇬" },
  { code: "MX", name: "Mexico", callingCode: "52", flag: "🇲🇽" },
  { code: "AR", name: "Argentina", callingCode: "54", flag: "🇦🇷" },
  { code: "CL", name: "Chile", callingCode: "56", flag: "🇨🇱" },
  { code: "CO", name: "Colombia", callingCode: "57", flag: "🇨🇴" },
  { code: "PE", name: "Peru", callingCode: "51", flag: "🇵🇪" },
  { code: "NL", name: "Netherlands", callingCode: "31", flag: "🇳🇱" },
  { code: "BE", name: "Belgium", callingCode: "32", flag: "🇧🇪" },
  { code: "CH", name: "Switzerland", callingCode: "41", flag: "🇨🇭" },
  { code: "AT", name: "Austria", callingCode: "43", flag: "🇦🇹" },
  { code: "SE", name: "Sweden", callingCode: "46", flag: "🇸🇪" },
  { code: "NO", name: "Norway", callingCode: "47", flag: "🇳🇴" },
  { code: "DK", name: "Denmark", callingCode: "45", flag: "🇩🇰" },
  { code: "FI", name: "Finland", callingCode: "358", flag: "🇫🇮" },
  { code: "PL", name: "Poland", callingCode: "48", flag: "🇵🇱" },
  { code: "PT", name: "Portugal", callingCode: "351", flag: "🇵🇹" },
  { code: "GR", name: "Greece", callingCode: "30", flag: "🇬🇷" },
  { code: "IE", name: "Ireland", callingCode: "353", flag: "🇮🇪" },
  { code: "NZ", name: "New Zealand", callingCode: "64", flag: "🇳🇿" },
];

module.exports = allCountries;